### ISSUE TITLE
[Feat] Allow configuring UI pages to display

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/web3inbox#101]
**Describe the solution you'd like**
- Pilot partners such as Spot are looking to leverage web3inbox SDK to bootstrap Push UI, without involving additional Chat functionality.
- web3Inbox should allow for configuring which pages to show, allowing for partners and users of web3inbox to only display functionality they support.

**Suggested implementation**
- Allow for passing UI params per page to configure pages, which are all enabled by default: `chatEnabled`, `settingsEnabled`, `pushEnabled`
- When a page is configured to be disabled, it won't display in the sidebar and won't be able to be navigated to. 
- The default page is now chosen in this order: 
  1. if chat enabled: `/messages`
  2. if push enabled: `/notifications`
  3. if settings enabled: `/settings`
  4. if none: `/login`

**Additional context**
- See thread: https://walletconnect.slack.com/archives/C03RWGSBCUU/p1682433835879819

**Comment by devceline** [comment]
Instead of making a push focused approach, a generic ui manipulation approach would be better for partners that will only want the chat ui

**Comment by bkrem** [comment]
> Instead of making a push focused approach, a generic ui manipulation approach would be better for partners that will only want the chat ui

@devceline Can you adjust the description pls based on what you've now implemented in terms of the more generic approach? 🙏
