### ISSUE TITLE
Send message fails when the invite is pending

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox#115]
**Describe the bug**
I've sent an invite to chat and I was able to send a message even though the invite was pending.
The message status was pending for a second and then it failed.

**To Reproduce**
1. Send an invite
2. Send a message while the invite is pending
3. See message status going from "pending" to "failed"

**Expected behavior**
Either disable chat box while invite is pending or keep message status as pending ?

**Screenshots**
![Screenshot_20230503_174003_Chrome](https://user-images.githubusercontent.com/32299095/235952524-b806a5f2-9adc-4cee-ab35-25c5c0561b8a.jpg)

**Comment by devceline** [comment]
Use case won't happen when this gets fixed https://github.com/WalletConnect/web3inbox/issues/135#issue-1709619020
