### ISSUE TITLE
Group subscriptions by app url.

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox#161]
**Is your feature request related to a problem? Please describe.**
A user could have multiple active subscriptions for the same dApp which results in duplicated app items. 

**Describe the solution you'd like**
Deduplicate apps by `metadata.url`

**Describe alternatives you've considered**
No alternative.

**Additional context**
See [Slack discussion](https://walletconnect.slack.com/archives/C03RWGSBCUU/p1686618258066779?thread_ts=1686493549.307949&cid=C03RWGSBCUU)

![IMG_9615](https://github.com/WalletConnect/web3inbox/assets/32299095/d7cadc40-7255-4e9d-bcc9-e1fc93ba96b7)

**Comment by devceline** [comment]
No longer relevant as the SDKs will prevent multiple subscriptions with the same url
