### ISSUE TITLE
Incorrect notification delivery time

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox#196]
**Describe the bug**
After a day not using the widget and opening it again, it shows that previous hourly gms were delivered now.

**To Reproduce**
1. Subscribe through the widget
2. Wait one or two hours without opening the widget
3. Open the widget again and see "now" for the notification delivery time

**Expected behavior**
The delivery time should be in the past (eg: 1 hour ago)

**Screenshots**
<img width="1792" alt="Capture d’écran 2023-08-11 à 10 34 52" src="https://github.com/WalletConnect/web3inbox/assets/32299095/f425e583-3adc-4501-ad62-1ec7c11e8153">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox

**Comment by devceline** [comment]
Looks like the state was wiped and refetched using history client

**Comment by devceline** [comment]
Fixed with latest notify version
