### ISSUE TITLE
fix: `notifyClient.register` and `chatClient.register` racing

### ISSUE THREAD

**Issue by arein** [WalletConnect/web3inbox#202]
**Describe the bug**
`notifyClient.register and chatClient.register were fired simultanously registering one identity key and storing another due to the order of them being fired`

CC @devceline 

Celine:

The 2 clients were racing to register, causing both of them to hit the `POST /identity` endpoint. Each with their own identity key. However, since they share the same identity key store, it caused them to sometimes store the wrong identity key.
**To Reproduce**
@devceline 

Just `localStorage.clear()` and try to register - it'll sometimes happen.

**Expected behavior**
State machine should not allow such races - not sure what the correct order is
@chris13524 can you help?

**Comment by chris13524** [comment]
Is this an error message? Sounds like to me W3I just needs to register once not twice? I know the SDKs are separated so this may be hard

**Comment by devceline** [comment]
Will be fixed with #186
