### ISSUE TITLE
Add filter based on verified/unverified domain for the notify explorer

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox#217]
**Is your feature request related to a problem? Please describe.**
For the upcoming hackathon, we need to be able to list dapps that don't have a verified domain yet but supports notify.

**Describe the solution you'd like**
A selector on the explorer that defaults to verified projects and gives the option to show unverified projects.

**Describe alternatives you've considered**
A branch that queries unverified projects and points to hack.web3inbox.com

**Additional context**
Needed for ETHGlobal New York

**Comment by devceline** [comment]
Has been added and resolved by #222
