### ISSUE TITLE
Improve start page after connecting

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/web3inbox#253]
After connecting with my wallet, I always land on https://app.web3inbox.com/notifications/, which is an empty page. 

<img width="1730" alt="image" src="https://github.com/WalletConnect/web3inbox/assets/707251/2b5ed1c9-3e2b-4958-ba3b-1146f1e8508b">

2 options to improve the experience:

A) Redirect users to the Discover page https://app.web3inbox.com/notifications/new-app 
B) Always show the latest notifications page (this carries the risk of users missing new notifications)

I advocate for option A.

Edit: Its possible this occurs only with wallets that have no new / latest notifications. Regardless of this, a user should always land on the Discover page first.

**Comment by devceline** [comment]
Closed with #254
