### ISSUE TITLE
Add Web Push Notifications

### ISSUE THREAD

**Issue by devceline** [WalletConnect/web3inbox#272]
**Is your feature request related to a problem? Please describe.**
Web3Inbox delivers the Notify API without actual web push, this needs to change to expand its feature set and deliver the expected UX

**Describe the solution you'd like**
Add Web Push functionality via FCM

**Describe alternatives you've considered**
Not implement web push and depend on a native app

```[tasklist]
- [ ] Have fault tolerant echo registration
  - [x] Not spammed on every subscribe
  - [x] Accounts for potentially different client IDs
- [x] Have symmetric symkeys synced for every subscription to indexed db
- [x] Have working FCM web push
- [x] Update Web3Inbox Prod to allow for web push
- [x] Remove old caching issues in service worker (remove caching for now)
- [x] Refactor to remove rudundant repeated code (Apply DRY principles)
- [x] Require notification permission in ways approved by MDN standards and browser implementations
  - [ ] test on firefox
  - [ ] test on chromium (and mobile chromium for Android)
  - [ ] test on safari (and mobile safari for iOS)
- [ ] Change App icon / favicon
```

**Additional context**
The push notifications have to work in desktop, android, iOS.

**Comment by herrhaase** [comment]
@devceline 
Added "Change app icon" to to-do's.

Assets here 
https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3797%3A32130&mode=design&t=dkphNVIcNFkyrbSS-1
