### ISSUE TITLE
P1: remove "Official app" from discover view

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3inbox#293]
Replace "Official app" with the app domain i.e. gm.walletconnect.com

![image](https://github.com/WalletConnect/web3inbox/assets/1979423/b5dc5316-6320-47f2-9e72-55212e138795)

Context: https://walletconnect.slack.com/archives/C044SKFKELR/p1701179393554649

**Comment by enesozturk** [comment]
Fixed
