### ISSUE TITLE
Subscribing will sometimes trigger a failure message but it show subscribed after

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#328]
**Describe the bug**
Subscribing will sometimes trigger a failure message but it show subscribed after

**To Reproduce**
1. Visit [app.web3inbox.com](http://app.web3inbox.com/)
2. Wipe out all localStorage and sessionStorage
3. Empty cache and hard reload
4. Enter Vercel password
5. Connect Wallet
6. Select WalletConnect
7. Sign message
8. Allow Notifications
9. Expect Subscribed apps from apps that I’ve used
   1. This was the first bug because I saw one app
   2. But I had more subscribed ones and they were missing
10. Subscribe to PancakeSwap
    1. Subscribed successfully to PancakwSwap
    2. suddenly my other missing subscriptions showed up
11. Unsubscribe all of them
12. Empty cache and hard reload
13. Enter Vercel password
14. Connect Wallet
15. Select Metamask
16. Sign Message
17. No subscribed apps
    1. This was working fine so no complains here
    2.
18. Subscribe to GM app
    1. This had a spinner on the button itself but it ended too quick
    2. The spinner stopped but the app didn’t show as subscribed
    3. A bit later the app shows as subscribed
19. Subscribe to PancakeSwap
    1. Same issue as before where the spinner stopped too quickly
    2. An error message showed “subscribe failed”
    3. Later the app showed as subscribed
20. Did a soft refresh of the page
21. The Wallet was still connected as expected
    1. However I noticed that I can see the discovery where apps show as unsubscribed
    2. I would expect here for the Discovery view to have a loading state
22. Tried the settings
    1. Added “display app on discover page”
    2. Typed “robots.farm”
    3. There was no feedback or toast when typing it
    4. This filtered out the other apps on Discovery
    5. Only saw Robots.farm on the Discovery page but expected it to be additive
    6. Then tried typing only “robots.far”
    7. Expected error message or any negative feedback but notihing happened
    8. Visited the discovery page and it was empty
    
**Expected behavior**

Successful subscription

**Screenshots**
n/a

**Additional context**
n/a

**Comment by enesozturk** [comment]
This will require more QA to be able to reproduce, should be fixed with our recent improvements but not 100% sure since we didn't make updates that address directly this issue.

**Comment by chadyj** [comment]
Looks good
