### ISSUE TITLE
Refreshing the Discovery page doesn’t have a loading state so apps show unsubscribed

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#329]
**Describe the bug**
Refreshing the Discovery page doesn’t have a loading state so apps show unsubscribed

**To Reproduce**
1. Subscribe to some apps
2. Go to discover page
3. Refresh the page

**Expected behavior**
The subscription button state shows correct status

**Actual behavior**
Subscirption state button changes after load

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by enesozturk** [comment]
We recently made improvements and due to lack of ability to handle the loading state for all subscriptions at once, we're going to show loading skeletons until the notify server handshake is done. 

So this should be closed once we merge https://github.com/WalletConnect/web3inbox/pull/362
