### ISSUE TITLE
Settings: Display app issues

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#330]
- [ ]  add a save button and save toast
- [x] The “display app on discovery page” should be additive instead of filtering out all other apps
- [ ] Trim leading/trailing spaces of value

**Comment by chris13524** [comment]
> The “display app on discovery page” should be additive instead of filtering out all other apps

This is fixed now.

> The “display app on discovery page” has no feedback when typing

Having a save button would be good here

**Comment by chadyj** [comment]
@enesozturk save button sounds good

**Comment by chadyj** [comment]
Also, the "display app" feature is broken if there is a leading or trailing space.
Can we trim the value?
