### ISSUE TITLE
Unsubscribing leads to blank page

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/web3inbox#343]
**Describe the bug**
Sporadically after unsubscribing user gets redirected to blank page

**To Reproduce**
1. Subscribe to gm-dapp in mobile chrome on ios
2. Unsubscribe from the gm-dapp in mobile chrome on ios
3. See blank page

**Expected behavior**
Not seeing blank page but either current subscriptions or discovery

**Screenshots**
![image](https://github.com/WalletConnect/web3inbox/assets/23137643/acf2463b-3744-4c71-9157-0fa9ec9a32de)

**Additional context**
Initially flagged by Tom [here](https://www.notion.so/walletconnect/WalletConnect-Existing-User-52fdf29933774083b3664513fc2fd1f1?pvs=4). Szymon wasn't able to reproduce

**Comment by devceline** [comment]
This has been fixed in later versions
