### ISSUE TITLE
Standalone PWA shows ◀Untitled instead of actual PWA name

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#376]
**Describe the bug**
Standalone PWA shows ◀Untitled instead of actual PWA name

**To Reproduce**

I couldn't reproduce this, but @amywilks234 reported it.

1. On ios, Go to app.web3inbox.com
2. Add to homescreen
3. Untitled will be shown

**Expected behavior**
"Web3Inbox" is shown.

**Screenshots**
![IMG_1131](https://github.com/WalletConnect/web3inbox/assets/116099/6693e9aa-15c9-44b2-872d-1bc0a04456b7)

**Desktop (please complete the following information):**
 - n/a

**Smartphone (please complete the following information):**
 - iOS
 - @amywilks234 reported 16.3.1

**Additional context**
The issue and a workaround is reported here https://stackoverflow.com/questions/72053298/standalone-pwa-shows-untitled-instead-of-actual-pwa-name

**Comment by devceline** [comment]
Can't reproduce this, iOS just uses the name of the app as you saved it. I think this is a one off from installing the app when it had bad metadata

**Comment by chadyj** [comment]
@devceline I think it is a bug on an earlier iOS version.
@amywilks234 reproduced with fixed metadata.

**Comment by devceline** [comment]
Ah, not much to do there then

**Comment by chadyj** [comment]
Closing this, since it relates to an older OS version, and only impacts a very small amount of people
