### ISSUE TITLE
Cannot scroll to bottom of subscriptions on iOS

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox#379]
**Describe the bug**
Cannot scroll to bottom of subscriptions on iOS

**To Reproduce**
1. Use iOS
2. Go to PWA
3. Have lots of subscriptions
4. Scroll 

**Expected behavior**
Smooth scrolling

**Screenshots**

https://github.com/WalletConnect/web3inbox/assets/116099/22b99b37-0f1e-4ac8-a3c1-a39119e96442

**Desktop (please complete the following information):**
 - n/a
 
**Smartphone (please complete the following information):**
 - Device: iOS

**Additional context**
n/a

**Comment by enesozturk** [comment]
@chadyj Appreciate if you can test this in this [Preview](https://app-web3inbox-git-refactor-subscriptions-9813c7-walletconnect1.vercel.app/)

**Comment by chadyj** [comment]
@enesozturk I could also reproduce both when in the notification tab viewing GMs
