### ISSUE TITLE
Show message to enable notifications if the user decline it

### ISSUE THREAD

**Issue by enesozturk** [WalletConnect/web3inbox#434]
Users might decline the first notification request, so maybe they might want it enabled back. So we could provide a UI to let users know that they disabled notifications and re-request to enable notifications. Maybe a switch in the settings page. 

Not urgent but would be a good touch. 

Related Sentry issue: https://walletconnect.sentry.io/issues/4959885127/?alert_rule_id=14621332&alert_type=issue&notification_uuid=14e28141-5ba3-4557-a831-1347d5850a48&project=4505754150043648&referrer=slack

This shouldn't trigger an error so I've created this if we decide to add it

**Comment by chris13524** [comment]
Isn't this what this switch is for?

![Screenshot 2024-02-09 at 15 03 31](https://github.com/WalletConnect/web3inbox/assets/1979423/6f8c2b50-1582-4cc4-bd20-f333b45a9ac2)
