### ISSUE TITLE
Add Brave as browser to automatically test in Playwright

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3inbox#444]
We will do the same for Web3Modal tests: https://github.com/WalletConnect/web3modal/issues/1951

https://walletconnect.notion.site/Web3Modal-Email-Broken-on-Brave-be2a045358194508bf727d276dd19814

**Comment by lukaisailovic** [comment]
Support for Brave is implemented in web3modal https://github.com/WalletConnect/web3modal/pull/1997

**Comment by chris13524** [comment]
Looks like this has been resolved as per above
