### ISSUE TITLE
Fix issues spotted in Design Review

### ISSUE THREAD

**Issue by devceline** [WalletConnect/web3inbox#59]
Issues spotted in design review meeting (excluding the more involved issues):

- [x] new chat icon too large
- [x] change placeholder in new chat space to slash
- [x] When inviting, it would go to the chat
- [x] messages start at the bottom and chat invite pending should be right above the input
- [x] messages should animate on appearance (mirrored for sender)
- [x] join messages that were sent less than header show time
- [x] MessageBox focus state (blue border)
- [x] Max width for the thread selector: 280px
- [x] Independent scroll for thread selector
- [x] Checkbox styling
- [x] Check icon in accepted should be white
- [x] Send invite disabled color is wrong
- [x] Send button color is wrong
- [x] Disabled button style incorrect in light mode
- [x] Checkbox is incorrect in lightmode
- [x] Hide invites when searching
- [x] Max message width in mobile should be 80%
- [x] too much space between input(MessageBox) and bottom
- [x] message timestamps should be further to the right
- [x] Transition animation between sign in and dapp
- [x] Include the notification bullet point on the hover area

cc @Cali93 @boidushya

**Comment by chadyj** [comment]
Also it looks like the Settings don't match Figma.
https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/web3inbox-standalone?node-id=251%3A16017&t=4Ls93Y9P9Wu6KIDv-1
