### ISSUE TITLE
Not easy to obtain wallet address w/o wallet app

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/web3inbox#81]
When in the messaging view of Web3Inbox, there is no easy way to obtain the wallet address, without Disconnecting or using your wallet app. This is particularly a blocker for Web3Account where there is no wallet app.

![image](https://user-images.githubusercontent.com/1979423/230620485-53c518fc-b11e-4fb6-9488-17018d404a04.png)

Requesting to either:
- add a copy button next to the address, or
- use the standard Web3Modal popup which already has a copy address button in it

https://walletconnect.slack.com/archives/C044SKFKELR/p1680809723151289?thread_ts=1680806893.688679&cid=C044SKFKELR

**Comment by chris13524** [comment]
Actually, you can already click the address to copy it to your clipboard, but this isn't obvious from the UI. Keeping this open because we still need some UI updates to make this user-friendly.

**Comment by devceline** [comment]
Added a copy button to the address to make it more obvious
